### ISSUE TITLE
Jackson deserialization error when making requests from vitrivr-ng to cineast

### ISSUE THREAD

**Issue by singaltanmay** [vitrivr/cineast#213] opened 2021-07-11 19:49 UTC
I am on the latest dev versions of both cineast and vitrivr-ng along with the latest docker image of cottontaildb. When making a image based request from vitrivr-ng to cineast i get the following errors in the cineast console - 

`WARN o.v.c.c.d.c.CottontailSelector - Error occurred during query execution in getUniqueValues(): INVALID_ARGUMENT: [878, d5612381-6ca1-4fb0-a28c-2b31b0de1580] EXECUTE QUERY failed because of binding error. Failed to bind FROM due to database error: Failed to bind 'warren.cineast.features'. Entity does not exist!`

`2021-07-11 18:30:13.420 [qtp1955587357-44] ERROR o.v.c.c.u.j.JacksonJsonProvider - Could not map JSON string '{"queries":[{"stages":[{"terms":[{"type":"IMAGE","categories":["globalcolor","localcolor","quantized"],"sliderSetting":1,"data":"data:image/png;base64,iVBORw..."}]}],"config":null}],"config":{"queryId":null,"hints":["exact"]},"timeDistances":[],"maxLength":600,"messageType":"Q_TEMPORALV2"}' to POJO. Please check your object definitions.`

`com.fasterxml.jackson.databind.exc.InvalidFormatException: Cannot deserialize value of type 'org.vitrivr.cineast.api.messages.interfaces.MessageType' from String "Q_TEMPORALV2": not one of the values accepted for Enum class: [QR_TEMPORAL, QR_SIMILARITY, QR_START, Q_SEG, Q_SIM, QR_ERROR, M_LOOKUP, Q_NESEG, PING, QR_SEGMENT, SESSION_START, QR_METADATA_O, QR_METADATA_S, Q_MLT, Q_TEMPORAL, QR_END, QR_OBJECT]`

**Comment by silvanheller** [comment] 2021-07-11 20:46
Thanks for the detailed & reproducible description! This should be fixed on `dev` (vitrivr-ng) now, it was caused because we removed the `V2` qualifier in Cineast (https://github.com/vitrivr/cineast/pull/203), but not in vitrivr-ng (https://github.com/vitrivr/vitrivr-ng/pull/78).

**Closed by silvanheller** 2021-07-11 20:46 UTC
Labels: bug
