### ISSUE TITLE
Memory leak while extracting OCRSearch

### ISSUE THREAD

**Issue by rahelarnold98** [vitrivr/cineast#273] opened 2022-03-03 17:02 UTC
When extracting the OCRSearch feature, the OOM Killer sometimes destroys the Java Process. The problem often occurs when not all machine resources are allocated for the extraction or too many threads are created for extraction purposes (sometimes four threads are too many, other times, the extraction completes with 16). In addition, the extraction often fails if additional features are extracted simultaneously.

A more detailed description of the occurring problem is following soon.

**Comment by silvanheller** [comment] 2022-06-07 17:42
Closing due to insufficient information. Can be reopened if the issue occurs and we have a reproducible bug report.

**Closed by silvanheller** 2022-06-07 17:42 UTC
