### ISSUE TITLE
Empty retriever list for query AudioQueryContainer

### ISSUE THREAD

**Issue by mamoudmatook** [vitrivr/cineast#90] opened 2019-09-04 08:38 UTC
Hello, below are the stack trace when I'm trying to execute an audio query 
the audio query was working and fine before last updates but now seems something went wrong I'm not sure exactly where or during which stage ( extraction or retrieving)
```
2019-09-04 21:18:59.446 [pool-5-thread-2] DEBUG o.v.c.a.w.h.a.AbstractWebsocketMessageHandler - Successfully wrote QR_END message to WebSocket stream!
2019-09-04 21:19:36.972 [pool-5-thread-2] DEBUG o.v.c.a.w.h.a.AbstractWebsocketMessageHandler - Successfully wrote QR_START message to WebSocket stream!
2019-09-04 21:19:36.996 [pool-5-thread-2] WARN o.v.c.c.u.ContinuousRetrievalLogic - Empty retriever list for query AudioQueryContainer[frames=[org.vitrivr.cineast.core.data.frames.AudioFrame@2554d0b7, org.vitrivr.cineast.core.data.frames.AudioFrame@5a52d6fe, org.vitrivr.cineast.core.data.frames.AudioFrame@5ce0a3c8, org.vitrivr.cineast.core.data.frames.AudioFrame@186f2d2a, org.vitrivr.cineast.core.data.frames.AudioFrame@1bbd97f8, org.vitrivr.cineast.core.data.frames.AudioFrame@57145757, org.vitrivr.cineast.core.data.frames.AudioFrame@eb3409e, org.vitrivr.cineast.core.data.frames.AudioFrame@6fd43a1f, org.vitrivr.cineast.core.data.frames.AudioFrame@1821624a, org.vitrivr.cineast.core.data.frames.AudioFrame@6d7a30f6, org.vitrivr.cineast.core.data.frames.AudioFrame@79593a77, org.vitrivr.cineast.core.data.frames.AudioFrame@3793e381, org.vitrivr.cineast.core.data.frames.AudioFrame@2433e40b, org.vitrivr.cineast.core.data.frames.AudioFrame@18728dfb, org.vitrivr.cineast.core.data.frames.AudioFrame@28c88600, org.vitrivr.cineast.core.data.frames.AudioFrame@efe773, org.vitrivr.cineast.core.data.frames.AudioFrame@3bc758d9, org.vitrivr.cineast.core.data.frames.AudioFrame@3756070f, org.vitrivr.cineast.core.data.frames.AudioFrame@5bc27f63, org.vitrivr.cineast.core.data.frames.AudioFrame@24e9df17, org.vitrivr.cineast.core.data.frames.AudioFrame@25695ac3, org.vitrivr.cineast.core.data.frames.AudioFrame@22804f1e, org.vitrivr.cineast.core.data.frames.AudioFrame@6af1054a, org.vitrivr.cineast.core.data.frames.AudioFrame@a6e64, org.vitrivr.cineast.core.data.frames.AudioFrame@6fda93e4, org.vitrivr.cineast.core.data.frames.AudioFrame@4f82d9be, org.vitrivr.cineast.core.data.frames.AudioFrame@2d3b4e51, org.vitrivr.cineast.core.data.frames.AudioFrame@7e116cdc, org.vitrivr.cineast.core.data.frames.AudioFrame@45ef8549, org.vitrivr.cineast.core.data.frames.AudioFrame@1c79eb63, org.vitrivr.cineast.core.data.frames.AudioFrame@6b47777b, org.vitrivr.cineast.core.data.frames.AudioFrame@1e459143, org.vitrivr.cineast.core.data.frames.AudioFrame@27b98a0f, org.vitrivr.cineast.core.data.frames.AudioFrame@74c84f68, org.vitrivr.cineast.core.data.frames.AudioFrame@24e40225, org.vitrivr.cineast.core.data.frames.AudioFrame@16994073, org.vitrivr.cineast.core.data.frames.AudioFrame@7d1b495d, org.vitrivr.cineast.core.data.frames.AudioFrame@4b1eea99, org.vitrivr.cineast.core.data.frames.AudioFrame@4fef3cf5, org.vitrivr.cineast.core.data.frames.AudioFrame@132977a3, org.vitrivr.cineast.core.data.frames.AudioFrame@345f853a, org.vitrivr.cineast.core.data.frames.AudioFrame@8a9eb0a, org.vitrivr.cineast.core.data.frames.AudioFrame@3e97667e, org.vitrivr.cineast.core.data.frames.AudioFrame@665b8a60, org.vitrivr.cineast.core.data.frames.AudioFrame@2ee5b5c4, org.vitrivr.cineast.core.data.frames.AudioFrame@69d3faa9, org.vitrivr.cineast.core.data.frames.AudioFrame@6c72d57b, org.vitrivr.cineast.core.data.frames.AudioFrame@56404a1f, org.vitrivr.cineast.core.data.frames.AudioFrame@55088e86, org.vitrivr.cineast.core.data.frames.AudioFrame@2378203c, org.vitrivr.cineast.core.data.frames.AudioFrame@59dbe025, org.vitrivr.cineast.core.data.frames.AudioFrame@d1f59b3],totalSamples=105984,totalDuration=4.806529,descriptor=org.vitrivr.cineast.core.data.frames.AudioDescriptor@4cab4423,weight=1.0,id=<null>,superId=<null>], category audiofingerprint and config org.vitrivr.cineast.core.config.QueryConfig@1cf29a28[
  queryId=7cfb1114-d3c0-40de-a1fb-754065df1902
  distance=<null>
  distanceWeights=<null>
  norm=NaN
  correspondence=<null>
  hints=[exact]
], returning no results
2019-09-04 21:19:37.009 [pool-5-thread-2] DEBUG o.v.c.a.w.h.a.AbstractWebsocketMessageHandler - Successfully wrote QR_END message to WebSocket stream!
```
any help is appreciated., 
below also are the contents of my job file and cineast config
```
{
    "database": {
         "host": "127.0.0.1",
         "port": 5890,
         "plaintext": true
     },


  "benchmark": {
    "mode": "OFF",
    "path": "benchmarks"
  },
  "retriever": {
    "threadPoolSize": 500,
    "maxResults": 200,
    "resultsPerModule": 250,
    "features": {
      "boolean" : [
        {"feature":  "DailyRangeBooleanRetriever", "weight": 1.0},
        {"feature":  "DailyCollectionBooleanRetriever", "weight": 1.0},
        {"feature":  "WSDMTICollectionBooleanRetriever", "weight": 1.0}
      ],
      "semantic" : [
        {"feature": "ConceptMasksAde20k", "weight" : 1.0}
      ],
      "globalcolor": [
        {"feature": "AverageColor",  "weight": 2.3},
        {"feature": "MedianColorRaster", "weight": 0.5},
        {"feature": "MedianColor", "weight": 1.2},
        {"feature": "AverageFuzzyHist", "weight": 0.7},
        {"feature": "AverageFuzzyHistNormalized", "weight": 0.7},
        {"feature": "HueHistogram", "weight": 0.7},
        {"feature": "MedianFuzzyHist",   "weight": 1.3 }
      ],
      "localcolor": [
        {"feature": "AverageColorARP44", "weight": 2},
        {"feature": "AverageColorARP44Normalized", "weight": 0.5},
        {"feature": "SubDivAverageFuzzyColor", "weight": 0.5},
        {"feature": "SubDivMedianFuzzyColor", "weight": 0.85},
        {"feature": "AverageColorGrid8", "weight": 1.8},
        {"feature": "AverageColorGrid8Normalized", "weight": 1.8},
        {"feature": "AverageColorCLD", "weight": 1.4},
        {"feature": "AverageColorCLDNormalized", "weight": 1.4},
        {"feature": "MedianColor", "weight": 1.0},
        {"feature": "CLD", "weight": 1.3},
        {"feature": "CLDNormalized", "weight": 1.3},
        {"feature": "MedianColorGrid8", "weight": 1.7},
        {"feature": "MedianColorARP44", "weight": 1.7},
        {"feature": "AverageColorRaster", "weight": 1.0}
      ],
      "edge": [
        {"feature": "EdgeARP88", "weight": 0.85},
        {"feature": "EdgeGrid16", "weight": 1.15},
        {"feature": "EHD", "weight": 0.7},
        {"feature": "DominantEdgeGrid16", "weight": 1.4},
        {"feature": "DominantEdgeGrid8", "weight": 1.4}
      ],
      "motion": [
        {"feature": "SubDivMotionHistogram3", "weight": 0.5},
        {"feature": "MotionHistogram", "weight": 0.5},
        {"feature": "SubDivMotionHistogram5", "weight": 0.5},
        {"feature": "SubDivMotionHistogramBackground3", "weight": 0.5},
        {"feature": "SubDivMotionHistogramBackground5", "weight": 0.5}
      ],
      "quantized": [
        {"feature": "AverageColorGrid8Reduced11", "weight": 1.0},
        {"feature": "AverageColorGrid8Reduced15", "weight": 1.0},
        {"feature": "AverageColorRasterReduced11", "weight": 1.0},
        {"feature": "AverageColorRasterReduced15", "weight": 1.0},
        {"feature": "CLDReduced11", "weight": 1.0},
        {"feature": "CLDReduced15", "weight": 1.0}
      ],
      "localfeatures": [
        {"feature": "SURFMirflickr25K512", "weight": 1.75},
        {"feature": "HOGMirflickr25K512", "weight": 1.0}
      ],
      "localfeatures_fast": [
        {"feature": "SURFMirflickr25K256", "weight": 1.75},
        {"feature": "HOGMirflickr25K256", "weight": 1.0}
      ],
      "audio": [
        {"feature": "CENS12Shingle", "weight": 1.0},
        {"feature": "AudioFingerprint", "weight": 1.0},
        {"feature": "HPCP12Shingle", "weight": 1.0},
        {"feature": "MFCCShingle", "weight": 1.0}
      ],
      "tagsft": [
        {"feature": "SegmentTags", "weight": 1.0}
      ],
      "ocr": [
        {"feature": "OCRSearch", "weight": 1.0}
      ],
      "text": [
                 {"feature": "SubtitleFulltextSearch","weight": 2.5}
      ]

    }
  },

  "decoders": {
    "VIDEO": {
      "decoder": "FFMpegVideoDecoder",
      "properties": {
        "maxFrameWidth": 640,
        "maxFrameHeight": 480,
	"subtitle": true
      }
    },
    "IMAGE": {
      "decoder": "DefaultImageDecoder",
      "properties": {
        "bounds": 1024
      }
    },
    "AUDIO": {
      "decoder": "FFMpegAudioDecoder",
      "properties": {
        "samplerate": 44100,
        "channels": 2
      }
    }
  },

  "extractor": {
    "threadPoolSize": 500,
    "outputLocation": "out"
  },

  "imagecache": {
    "softMemoryLimit": 2048,
    "hardMemoryLimit": 1024
  },

  "api": {
    "enableCLI": true,
    "enableWebsocket": true,
    "enableWebsocketSecure": false,
    "enableRest": true,
    "enableRestSecure": false,
    "enableLegacy": false,
    "maxMessageSize": 40960000,
    "httpPort": 4567,
    "httpsPort": 4568,
    "legacyPort": 12345,
    "threadPoolSize": 500,
    "serveContent": true,
    "serveUI": true,
    "uiLocation": "/var/www/html",
    "thumbnailLocation": "thumbnails",
    "objectLocation": "objects"
  },

  "visualization": {
    "cacheEnabled": false,
    "cachePath": "cache/art/"
  },

  "monitoring":{
    "enablePrometheus": true,
    "prometheusPort": 4569
  }

}
```
 *************
job file
```
{
	"type":"VIDEO",
	"input":{
		"path": "objects",
		"depth":3,
		"skip": 0,
		"id": {
			"name": "SequentialObjectIdGenerator",
			"properties": {}
		}
	},
	"extractors":[
		/* Visual features: */
		{"name": "AverageColor"},
		{"name": "AverageColorARP44"},
		{"name": "AverageColorCLD"},
		{"name": "AverageColorGrid8"},
		{"name": "AverageColorRaster"},
		{"name": "AverageFuzzyHist"},
		{"name": "CLD"},
		{"name": "EdgeARP88"},
		{"name": "EdgeGrid16"},
		{"name": "EHD"},
		{"name": "MedianColor"},
		{"name": "MedianColorARP44"},
		{"name": "MedianColorGrid8"},
		{"name": "MedianColorRaster"},
		{"name": "MotionHistogram"},
		{"name": "HOGMirflickr25K512"},
		{"name": "SURFMirflickr25K512"},
		{"name": "SubtitleFulltextSearch"},
		{"name": "OCRSearch"},

		/* Audio features: */
		{"name": "AudioFingerprint"},
		{"name": "CENS12Shingle"},
		{"name": "HPCP12Shingle"},
		{"name": "MFCCShingle"}

	
	],
	"exporters":[
		{
			"name": "AudioSegmentExporter",
			"properties": {
				"destination": "thumbnails"
			}
		},
		{
			"name": "ShotThumbNails",
			"properties": {
				"destination": "thumbnails"
			}
		}
	]
	}
```

**Comment by silvanheller** [comment] 2019-09-04 08:42
Can you share your UI config / version? from a glance, it looks like the UI uses the `audiofingerprint` category whereas in your config, the category is `audio`

**Comment by mamoudmatook** [comment] 2019-09-04 08:45
`{
  "api": {
    "host" : "localhost",
    "port" : 4567,
    "protocol_http": "http",
    "protocol_ws": "ws",
    "ping_interval": 10000
  },
  "resources": {
    "host_thumbnails" : "/home/Maatuq/MultiMediaResarch/cineast/build/libs/thumbnails",
    "host_objects": "/home/Maatuq/MultiMediaResarch/cineast/build/libs/objects",
    "suffix_default":"jpg",
    "suffix": {
      "IMAGE": "png",
      "VIDEO": "png"
    }
  },
  "vbs": {
    "active": true,
    "teamid": 2,
    "toolid": null,
    "endpoint": "127.0.0.1:3100/lsc/submit",
    "collabordinator": null
  },
  "evaluation": {
    "active":false,
    "templates": [
      {
        "name": "Test","url": "http://localhost:4200/evaluation.json"
      }
    ]
  },
  "mlt" : ["globalcolor", "localcolor", "edge"],
  "query": {
    "history": 5,
    "options": {
      "image": true,
      "audio": true,
      "model3d": true,
      "motion": true,
      "text": true,
      "tag": true,
      "semantic": true,
      "boolean": true
    },
    "config": {
      "hints": ["exact"],
      "neighboringSegmentLookupCount": 5,
      "neighboringSegmentLookupAllCount": 2000
    },
    "text": {
      "categories": [
        ["ocr", "Text on Screen"],
        ["tagsft", "Tags"],
        ["subtitle","subtitle"]
      ]
    },
    "boolean": [
      ["Location", "TEXT", "features_daily.location"],
      ["Skin Temperature", "NUMERIC", "features_daily.skin_temp"],
      ["Heart Rate", "NUMERIC", "features_daily.heart_rate"],
      ["Calories", "NUMERIC", "features_daily.calories"],
      ["GSR", "NUMERIC", "features_daily.gsr"],
      ["Steps", "NUMERIC", "features_daily.steps"],
      ["Annotation", "TEXT", "features_wsdmtiannotations.annotation"],
      ["Object", "TEXT", "features_wsdmtiannotations.object"]
    ]
  }
}
`

**Comment by silvanheller** [comment] 2019-09-04 08:47
What is the output of `git status` in the ui-repo?

**Comment by mamoudmatook** [comment] 2019-09-04 08:48
`

On branch master
Your branch is up to date with 'origin/master'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   package-lock.json
	modified:   src/config.json

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	deploy.log
	deploy/

no changes added to commit (use "git add" and/or "git commit -a")

`

**Comment by silvanheller** [comment] 2019-09-04 08:51
Can you try changing the categoryname `audio` to `audiofingerprint` in your cineast-config?

**Comment by mamoudmatook** [comment] 2019-09-04 08:56
Ok thanks a lot for you support,
but there still the same issue for text queries
below are the stack trace when I try to issue text query
even .srt files with the same name are there.

`
2019-09-04 21:51:00.566 [pool-5-thread-2] DEBUG o.v.c.a.w.h.a.AbstractWebsocketMessageHandler - Successfully wrote QR_END message to WebSocket stream!
2019-09-04 21:51:37.083 [pool-5-thread-2] DEBUG o.v.c.a.w.h.a.AbstractWebsocketMessageHandler - Successfully wrote QR_START message to WebSocket stream!
2019-09-04 21:51:37.084 [pool-5-thread-2] WARN o.v.c.c.u.ContinuousRetrievalLogic - Empty retriever list for query TextQueryContainer[text=emotional,weight=1.0,id=<null>,superId=<null>], category subtitle and config org.vitrivr.cineast.core.config.QueryConfig@171e779a[
  queryId=4d2293af-39b6-47c5-9368-8de321f80ba2
  distance=<null>
  distanceWeights=<null>
  norm=NaN
  correspondence=<null>
  hints=[exact]
], returning no results
2019-09-04 21:51:37.099 [pool-6-thread-5] DEBUG o.v.c.c.r.RetrievalTask - starting SegmentTags
2019-09-04 21:51:37.099 [pool-6-thread-5] DEBUG o.v.c.c.r.RetrievalTask - SegmentTags.getSimilar() done in 1 ms
2019-09-04 21:51:37.121 [pool-6-thread-6] DEBUG o.v.c.c.r.RetrievalTask - starting OCRSearch
2019-09-04 21:51:37.134 [pool-6-thread-6] ERROR o.v.c.c.d.a.ADAMproSelector - Query returned non-OK result code ERROR with message: Entity 'features_ocr' not existing.
2019-09-04 21:51:37.137 [pool-6-thread-6] DEBUG o.v.c.c.r.RetrievalTask - OCRSearch.getSimilar() done in 16 ms
2019-09-04 21:51:37.152 [pool-5-thread-2] DEBUG o.v.c.a.w.h.a.AbstractWebsocketMessageHandler - Successfully wrote QR_END message to WebSocket stream!

`

**Comment by silvanheller** [comment] 2019-09-04 09:03
Same issue, cineast is looking for a `category subtitle` and in your config the category is called text:
```      
"text": [
                 {"feature": "SubtitleFulltextSearch","weight": 2.5}
      ]
``` 
The problem could be fixed by changing the relevant config line to subtitle:
```
"subtitle": [
                 {"feature": "SubtitleFulltextSearch","weight": 2.5}
      ]
```

**Comment by mamoudmatook** [comment] 2019-09-04 09:06
thanks
but another error
ected!
2019-09-04 22:02:27.385 [pool-5-thread-2] DEBUG o.v.c.a.w.h.a.AbstractWebsocketMessageHandler - Successfully wrote QR_START message to WebSocket stream!
2019-09-04 22:02:27.392 [pool-6-thread-1] DEBUG o.v.c.c.r.RetrievalTask - starting SubtitleFulltextSearch
2019-09-04 22:02:27.404 [pool-6-thread-1] ERROR o.v.c.c.d.a.ADAMproSelector - Query returned non-OK result code ERROR with message: Entity 'features_asr' not existing.
2019-09-04 22:02:27.406 [pool-6-thread-1] DEBUG o.v.c.c.r.RetrievalTask - SubtitleFulltextSearch.getSimilar() done in 14 ms
2019-09-04 22:02:27.457 [pool-5-thread-2] DEBUG o.v.c.a.w.h.a.AbstractWebsocketMessageHandler - Successfully wrote QR_END message to WebSocket stream!
`

`

**Comment by silvanheller** [comment] 2019-09-04 09:17
Do the queries for audio return results? One of the workflow issues with cineast is that entities are not automatically created on extraction. This means the extraction workflow for cineast is as follows:

1. Perform the `setup` command: `java -jar ... --setup`, if you wish to to drop all existing entries, the command is `... --setup clean=true` 
2. Run Extraction (Make sure that all features in your job are included in your config file as the setup command only creates entities in your config)
3. Retrieval

Therefore, it seems to me that you did not run the setup command before the extraction, which means that no data was written to the database during extraction.

**Comment by mamoudmatook** [comment] 2019-09-04 09:24
1-yes, audio returned results
2- I'll try and comeback later 
3- results that returned appeared like the attached  screenshot below 
I'm sure that for thumbnails path and objects are correct you also could make sure 
from above UI config.
4- i noticed that UI try to retrieve something that is .mp4 from thumbnail 
but what actually in my thumbnail directory is all .wav or .png

![1](https://user-images.githubusercontent.com/9833150/64242536-04469a00-cf06-11e9-8c21-ad2b16469961.png)

**Comment by mamoudmatook** [comment] 2019-09-04 09:29
regarding OCR and subtitle below is stack trace of running cineast with the option --setup
`
2019-09-04 22:21:46.874 [main] INFO o.v.c.c.s.EntityCreator - Setting up SubtitleFulltextSearch
2019-09-04 22:21:46.905 [main] ERROR o.v.c.c.s.EntityCreator - Error while creating entity features_asr: 'failing on handler solr:org.apache.solr.client.solrj.impl.HttpSolrClient$RemoteSolrException: Error from server at http://localhost:8983/solr: Error CREATEing SolrCore 'features_asr_14': Unable to create core [features_asr_14] Caused by: Could not load configuration from directory /usr/lib/solr/server/solr/configsets/_default'

`

*****************
`
2019-09-04 22:21:46.798 [main] INFO o.v.c.c.s.EntityCreator - Setting up OCRSearch
2019-09-04 22:21:46.842 [main] ERROR o.v.c.c.s.EntityCreator - Error while creating entity features_ocr: 'failing on handler solr:org.apache.solr.client.solrj.impl.HttpSolrClient$RemoteSolrException: Error from server at http://localhost:8983/solr: Error CREATEing SolrCore 'features_ocr_877': Unable to create core [features_ocr_877] Caused by: Could not load configuration from directory /usr/lib/solr/server/solr/configsets/_default'

`

**Comment by silvanheller** [comment] 2019-09-04 09:33
As luca already said on the mailinglist, your thumbnail issue stems from two things: 1) you need to setup a webserver, e.g. apache2 and host the thumbnails / objects there. Browsers do not allow you to access local files.
2) Your suffix configuration in the UI is incorrect. Change 
```
    "suffix": {
      "IMAGE": "png",
      "VIDEO": "png"
    }
```
to 
```
    "suffix": {
      "IMAGE": "png",
      "VIDEO": "png",
     "AUDIO": "wav"
    }
```

**Comment by silvanheller** [comment] 2019-09-04 09:39
Re: Setup, this is a known issue, please try the solution on the wiki https://github.com/vitrivr/ADAMpro/wiki/3.-Troubleshooting

**Comment by mamoudmatook** [comment] 2019-09-04 09:44
1- for thumbnails I changed the path yesterday before that it was already on root directory of apache2 running on my machine (/var/www/html) and the problem was already there. 
2- just to double-check regarding "suffix"
should the video be .mp4, as UI results trying to retrieve a .mp4 file that is not there?
All files inside thumbnails are .mp4 and .wav
![1](https://user-images.githubusercontent.com/9833150/64244482-694fbf00-cf09-11e9-9d86-a3bbe8586582.png)

**Comment by silvanheller** [comment] 2019-09-04 11:11
1:
Your UI config is wrong. It says 
```
    "host_thumbnails" : "/home/Maatuq/MultiMediaResarch/cineast/build/libs/thumbnails",
    "host_objects": "/home/Maatuq/MultiMediaResarch/cineast/build/libs/objects",
```
instead of a link to the webserver, e.g.
```
    "host_thumbnails" : "http://localhost/thumbnails/:o/:s:x",
    "host_objects": "http://localhost/objects/:p",
```
For a complete list of supported templating strings, check the `resolver.service.ts` in the vitrivr-ng repo
2: you can configure the suffix. But the AudioSegmentExporter is not intended to be used as a thumbnail, since it exports audio and not images. It makes no sense to use .wav-files as thumbnails.

**Comment by mamoudmatook** [comment] 2019-09-04 11:13
thanks a lot for your support.
I'll try that and come back soon.

**Comment by mamoudmatook** [comment] 2019-09-10 09:21
HI,
Now it's up and running except for subtitle search, even extraction goes well and a .srt file with the same name of videos are there at the same folder it seems no vector features returned.
below stack trace when try to search by subtitle.
`
2019-09-10 22:13:57.415 [pool-6-thread-28] DEBUG o.v.c.c.r.RetrievalTask - starting SubtitleFulltextSearch
2019-09-10 22:13:57.457 [pool-6-thread-28] DEBUG o.v.c.c.r.RetrievalTask - SubtitleFulltextSearch.getSimilar() done in 42 ms
2019-09-10 22:13:57.470 [pool-5-thread-2] DEBUG o.v.c.a.w.h.a.AbstractWebsocketMessageHandler - Successfully wrote QR_END message to WebSocket stream!

`

**Comment by silvanheller** [comment] 2019-09-10 13:13
Can you please check via the ADAMpro UI @ localhost:9099 for the contents of the subtitle entity? To me, this looks like the entity is empty.

**Comment by mamoudmatook** [comment] 2019-09-10 13:36
Hello, 
yes it's empty and I don't know why.
note: solr is up and running and there was no error regarding feature SubtitleFulltextSearch during extraction.
but when I check solr web interface there was already 2 cores 
1- features_ocr
2-features_asr 
but both of them were empty I mean there was no indexed documents there.
BTW entity corresponding to SubtitleFulltextSearch is "features_asr"
![2](https://user-images.githubusercontent.com/9833150/64618564-ca333780-d3e0-11e9-958e-adff803c020f.png)
![1](https://user-images.githubusercontent.com/9833150/64618566-ca333780-d3e0-11e9-8d4b-1e54f8138db0.png)

**Comment by silvanheller** [comment] 2019-09-10 13:49
We'll have a look internally at your issue. But it's challenging to debug such an issue remotely, i suggest you have a look yourself at what cineast does during extraction using e.g. a debugger in intellij. If we manage to find your issue, we'll let you know.

**Comment by mamoudmatook** [comment] 2019-09-10 13:57
Ok, thanks a lot for your support.
but I have some questions, 
1- is subtitle search really supported, does anyone used it via vitrivr before.
2-should i submit subtitle files in .srt or it should be in a  solr-supported format like ( Json, XML ....) 
3-I have some confusions regarding feature name inside cineas.json  and it's corresponding entity name at Adampro  and category name in UI config how could i make sure i'm using the same that will match in all of the previous config files ( I hope I'm clear here)
4-If I wanted to start debugging session regarding SubtitleFulltextSearch which classes insid feature blokc and api block should i look or take care first.

**Comment by mamoudmatook** [comment] 2019-10-06 18:21
Hello, 
any updates here??

**Comment by silvanheller** [comment] 2019-10-07 06:24
Hi mamoudmatook, vitrivr is an open source project. As such, you are welcome to ask questions, download the code and play around with it, and contribute. The code is written in Java and you are free to debug it using any tool you'd like, for example IntelliJ has an excellent debugger. As I wrote in my last comment, it's challenging to debug issues remotely.

Coming to your questions, 2 and 3 can be directly answered by looking at the code, and as for 4, there's literally a class called SubtitleFulltextSearch. As for 1, yes it is supported. There might be some bugs, and if we have a clear and reproducible bugreport, we'll do our best to fix it. 

I'm closing this issue because it does not contain a bug report with clear reproduction instructions but is rather the kind of open-ended discussion better suited for the mailinglist. If you can provide us with instructions on how to reproduce your issue, feel free to open a new issue.

**Closed by silvanheller** 2019-10-07 06:24 UTC
